# This is a multi-stage Dockerfile for building a PyTorch training image inspired from the docs published by UV
# multi layer building most of the defaults are adapted as verbatim.

FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS builder

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy


COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-install-project


FROM python:3.13-slim AS training

WORKDIR /app


COPY --from=builder /app/.venv /app/.venv


COPY src/ ./src/
COPY configs/ ./configs/


RUN mkdir -p /app/data /app/checkpoints

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

ENTRYPOINT ["python", "src/train.py"]
